---
- name: install common packages, rabbitmq and erlang
  hosts: instance-1,instance-2,instance-3
  roles:
    - base-setup
    - common-package

- name: run copy erlang cookie task
  hosts: instance-1
  roles:
    - erlang-cookie 

- name: run join cluster task
  hosts: instance-2,instance-3
  roles:
    - join-cluster

- name: run user add/remove and add ha policies task
  hosts: instance-1
  roles:
    - user-add-ha-policies


