---
- name: install common packages, rabbitmq and erlang
  become: yes
  hosts: instance1:instance2:instance3
  roles:
    - base-setup
    - common-package

- name: run copy erlang cookie task
  become: yes
  hosts: instance1
  roles:
    - erlang-cookie 

- name: run join cluster task
  become: yes
  hosts: instance2:instance3
  roles:
    - join-cluster

- name: run user add/remove and add ha policies task
  become: yes
  hosts: instance1
  roles:
    - user-add-ha-policies


