---
- name: install
  hosts: instance-1,instance-2,instance-3
  roles:
    - base_setup
    - rabbit-mq
  tags:
    - common

- name: run copy erlang cookie task
  hosts: instance-1
  roles:
    - rabbit-mq
  tags:
    - copy-erlang-cookie  

- name: run join cluster task
  hosts: instance-2,instance-3
  roles:
    - rabbit-mq
  tags:
    - join-cluster

- name: run user add/remove and add ha policies task
  hosts: instance-1
  roles:
    - rabbit-mq
  tags:
    - user-add-remove
    - add-ha-policies


