---
# tasks file for base_setup
    - name: Base setup
      apt: 
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - curl
        - telnet 
        - htop
        #- software-properties-common
        - bzip2
      tags: common
