---
# tasks file for rabbitmq setup

- name: Install nessesary package
  apt: 
      name: apt-transport-https
      state: present
      update_cache: yes

- name: Download esl-erlang package
  get_url:
    url: https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_21.0-1~debian~stretch_amd64.deb
    dest: /data/esl-erlang_21.0-1~debian~stretch_amd64.deb

- name: Install esl-erlang
  apt:
    deb: /data/esl-erlang_21.0-1~debian~stretch_amd64.deb

- name: Download erlang solutions
  get_url:
    url: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    dest: /data/erlang-solutions_1.0_all.deb

- name: Install erlang repository
  apt:
    deb: /data/erlang-solutions_1.0_all.deb

- name: Add an Apt signing key
  apt_key:
    url: https://packages.erlang-solutions.com/debian/erlang_solutions.asc
    state: present

- name: fix unmet dependencies
  shell: apt-get -f install

- name: Add rabbit repo
  shell: echo "https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ bionic main" | tee /etc/apt/sources.list.d/rabbitmq.list

- name: add trusted key
  shell: wget -O- https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey | sudo apt-key add -

- name: install rabbitmq
  apt: 
    name: rabbitmq-server
    state: present
    update_cache: yes

- name: enable rabbitmq plugins
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  notify:
    - restart rabbitmq

#- name: add rabbitmq users admin
#  rabbitmq_user:
#    user: admin
#    password: superpassword
#    vhost: /
#    tags: administrator
#    configure_priv: .*
#    read_priv: .*
#    write_priv: .*
#    state: present
  
# If it's not necessary use rabbitmq_exporter uncoment 
# - name: remove default guest user
#   rabbitmq_user: 
#     user: guest
#     state: absent
