---
# tasks file for rabbitmq setup
- name: Download esl-erlang package
  get_url:
    url: https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_24.0.1-1~ubuntu~bionic_amd64.deb
    dest: /data/esl-erlang_24.0-1-1~ubuntu~bionic_amd64.deb
  tags: common

- name: Install esl-erlang
  apt:
    deb: /data/esl-erlang_24.0-1-1~ubuntu~bionic_amd64.deb
  tags: common

- name: Download erlang solutions
  get_url:
    url: https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
    dest: /data/erlang-solutions_2.0_all.deb
  tags: common

- name: Install erlang repository
  apt:
    deb: /data/erlang-solutions_2.0_all.deb
  tags: common

- name: Add an Apt signing key
  apt_key:
    url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    state: present
  tags: common

- name: fix unmet dependencies
  shell: sudo apt-get -f install
  tags: common

- name: Add rabbit repo
  shell: echo "https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ bionic main" | tee /etc/apt/sources.list.d/rabbitmq.list
  tags: common

- name: add trusted key
  shell: wget -O- https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey | sudo apt-key add -
  tags: common

- name: install rabbitmq
  apt: 
    name: rabbitmq-server
    state: present
    update_cache: yes
  tags: common

- name: enable rabbitmq plugins
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  notify:
    - restart rabbitmq
  tags: common

- name: add rabbitmq user admin and delete guest user
  rabbitmq_user:
    user: hakase
    password: aqwe123@
    vhost: /
    tags: administrator
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  rabbitmq_user: 
    user: guest
    state: absent
  tags: user-add-remove

- name: join cluster node2 and node3 to node1
  shell: |
    sudo systemctl restart rabbitmq-server
    sudo rabbitmqctl stop_app
    sudo rabbitmqctl join_cluster rmquser@rmq-1.westeu.internal
    sudo rabbitmqctl start_app
    sudo rabbitmqctl cluster_status
  tags: join-cluster

- name: copy erlang cookie from node1 to node2 and node3
  shell: |
    sudo scp /var/lib/rabbitmq/.erlang.cookie rmquser@rmq-2.westeu.internal:/var/lib/rabbitmq/
    sudo scp /var/lib/rabbitmq/.erlang.cookie rmquser@rmq-3.westeu.internal:/var/lib/rabbitmq/
  tags: copy-erlang-cookie

- name: add ha policies
  shell: |
    sudo rabbitmqctl set_policy ha-all ".*" '{"ha-mode":"all"}'
    sudo rabbitmqctl set_policy ha-two "^two\." '{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}'
    sudo rabbitmqctl set_policy ha-nodes "^nodes\." '{"ha-mode":"nodes","ha-params":["rmquser@rmq-2.westeu.internal", "rmquser@rmq-3.westeu.internal"]}'
    sudo rabbitmqctl list_policies;
  tags: add-ha-policies

