---
- name: copy erlang cookie from node1 to node2 and node3
  shell: |
    sudo scp -i /home/kafkauser/azure-eu-environment/keys/rmq_routing /var/lib/rabbitmq/.erlang.cookie rmquser@rmq-2.westeu.internal:.
    sudo scp -i /home/kafkauser/azure-eu-environment/keys/rmq_routing /var/lib/rabbitmq/.erlang.cookie rmquser@rmq-3.westeu.internal:.
  tags: copy-erlang-cookie